### PR TITLE
Include lib/ into the npm package

### PR DESCRIPTION
**Pull request by eush77**
I've just got the `Cannot find module './lib/exp'` error.

### CODE REVIEW

**Comment by hemanth** [comment]
@eush77 Came here to fix this :+1: 

This is breaking all dependent modules.

//cc @jonschlinkert Get well soon.

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
I just pushed up a new version. sorry for breaking the internet!

**Comment by hemanth** [comment]
:+1:

**Comment by jonschlinkert** [comment]
@hemanth, would you want to be added as a collab on this? would be great to have another dev around when something breaks, if I can't get to it fast enough.

**Comment by hemanth** [comment]
@jonschlinkert Sure! My pleasure :)

**Comment by jonschlinkert** [comment]
Done! thanks, I appreciate it!

**Comment by hemanth** [comment]
Thanks :+1:

**Pull request merged**
